### ISSUE TITLE
Missing script definitions for yarn

### ISSUE THREAD

**Issue by mgsmyth** [4-point-0/raidar-backend#42]
Hitting errors when I run `yarn test`, `yarn start`, etc.

`Usage Error: Couldn't find a script named "test".`

**Comment by rimatik** [comment]
I'll update README.md, "yarn test" should work normally from root of raidar-backend folder, "yarn start" only works if nest app is built. Use "yarn start:dev" to test locally and for production there should be pipeline where first "yarn build" is triggered and than "yarn start"
